app = "bridge-app"
primary_region = "ewr"

[build]

[env]
  PORT = "8080"
  SQLITE_PATH = "./src/data/bridges.db"
  MODEL_CHECKPOINT_PATH = "results/checkpoints/t5-small_best.pth"
  UPLOAD_DIR = "./uploads"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  min_machines_running = 1

[[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "10s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/uploads"
  url_prefix = "/uploads"

